### PR TITLE
fix: switch from experimental_memo to cache_data

### LINKED ISSUE #34: Python errors
Hey thanks for sharing your project

I see errors online for the first 3 pages

https://ssg-dataset.streamlit.app/

Screenshot 2024-10-31 at 03 02 13

> AttributeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:

```
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/mount/src/ssg-dataset/app/Static_site_generators.py", line 4, in <module>
    from data import get_data, get_github_scale
File "/mount/src/ssg-dataset/app/data.py", line 9, in <module>
    @st.experimental_memo
```

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
I believe the docs say that this is the fix for the breakage I reported in #34 

Fixes: #34 

Screen-recording:

https://github.com/user-attachments/assets/d4232fd1-55a4-40fd-a525-7c2f0bf3a051

### CODE REVIEW

**Comment by epogrebnyak** [comment]
great, thanks, lets see if the app updates!

**Comment by Lewiscowles1986** [comment]
Is there a reason it would?

I don't see any GitHub actions here, but I'm also incredibly gree on streamlit.

Thanks for the hint as to what might be wrong.

**Comment by epogrebnyak** [comment]
The streamlit app that is hosted on their cloud takes the code from the rpo, so on rerun or after sleep it takes newer code. Seems to work now - can you check?

**Comment by Lewiscowles1986** [comment]
Yeah all working. Thanks.

**Comment by epogrebnyak** [comment]
Thanks for the patch!

**Pull request merged**
